package com.example.xlsformlab.core

import java.time.Instant
import java.util.UUID

/**
 * Minimal provenance envelope for evidence generated by a capability execution.
 */
data class Provenance(
    val runId: String = UUID.randomUUID().toString(),
    val generatedAt: String = Instant.now().toString(),
    val capabilityId: String,
    val capabilityVersion: String,
    val activityIds: List<String> = emptyList(),
    val transport: String? = null,
    val warnings: List<String> = emptyList()
)
